import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import SiteHeader from "../../components/site-header";
import CaseStudyTopline from "../../components/case-study-topline";
import PortfolioFooter from "../../components/portfolio-footer";
import BrandDemo from "./brand-demo";
import styles from "./system.module.css";
export const metadata: Metadata = { title: "Multi-brand design system — Lisa Huang", description: "運用 AI 整理既有產品色彩系統，建立色票、Design Tokens 與開發取代對照，延伸多品牌樣版。" };
function Evidence({name,alt,width=2000,height=1200}:{name:string;alt:string;width?:number;height?:number}) { return <a className={styles.evidence} href={`/projects/design-system/${name}.webp`} target="_blank" rel="noreferrer" aria-label={`${alt}，開啟完整圖片`}><Image unoptimized src={`/projects/design-system/${name}.webp`} alt={alt} width={width} height={height} sizes="100vw"/><span>查看完整圖片 ↗</span></a>; }
function MiniUI({variant=0}:{variant?:number}) {return <div className={`${styles.mini} ${styles[`variant${variant}`]}`}><div className={styles.miniBar}>PRODUCT <span>● ● ●</span></div><p>My account</p><h3>Welcome back</h3><div className={styles.fakeInput}>Account name</div><div className={styles.fakeButton}>Continue →</div><small>Home　　Activity　　Account</small></div>;}
export default function DesignSystemCase(){return <main className={styles.page}>
  <SiteHeader alwaysVisible/>
  <header className={styles.hero}><CaseStudyTopline number="02" context="Design system · AI-assisted workflow"/><p className={styles.label}>EVOLVING AN EXISTING PRODUCT</p><h1>One system.<br/><em>Many brands.</em></h1><div className={styles.heroIntro}><p>用 AI 整理歷史累積的設計規範，<br/>讓設計與開發回到同一套色彩語言。</p><span>色彩系統整理 / 開發交付 / 品牌延伸</span></div><div className={styles.heroVisual}><div><span className={styles.label}>FROM FRAGMENTS TO A SHARED FOUNDATION</span><h2>整理規則，<br/>延伸品牌。</h2><div className={styles.swatches}>{['#070B13','#142238','#22395E','#2F4F83','#3D66A9','#5F86C5','#83A2D2','#A9BEE0','#CEDAED','#ECF1F8'].map(c=><i key={c} style={{background:c}}/>)}</div><p>Primary / Neutral / State</p></div><div className={styles.heroCard}><code>primary-06</code><strong>#5F86C5</strong><span>Design tokens → Brand templates</span><div className={styles.brandDots}><i/><i/><i/></div></div></div></header>
  <section className={styles.section}><div className={styles.sectionHead}><p className={styles.label}>01 / THE CHALLENGE</p><h2>同一份設計，<br/><span>不同的實作結果。</span></h2></div><p className={styles.lead}>公版 UI 分配給不同開發部門，分別進行 Mobile 與 App 開發。設計檔案歷史久遠、缺乏系統性管理，讓看似相近的樣式與顏色，在實作後逐漸產生差異。</p><div className={styles.flowSource}><span>公版設計</span><p>相同 UI，交付不同開發部門</p><b>↓</b></div><div className={styles.compare}><article><p className={styles.label}>TEAM A / MOBILE</p><MiniUI variant={0}/><p>色值、間距與元件細節各自解讀</p></article><article><p className={styles.label}>TEAM B / APP</p><MiniUI variant={1}/><p>視覺相似，實際定義逐漸分歧</p></article></div><p className={styles.caption}>痛點概念示意，非歷史產品截圖；色值、圓角及間距差異用於說明跨部門實作偏差。</p></section>
  <section className={`${styles.section} ${styles.tinted}`}><div className={styles.sectionHead}><p className={styles.label}>02 / CONNECT THE SOURCES</p><h2>從分散的定義，<br/><span>找到共同依據。</span></h2></div><div className={styles.sourceGrid}><div><h3>設計端的色票</h3><p>整理目前產品的 Primary、Neutral、State 與專區色彩，讓色值有可查找的分類。</p><Evidence name="color-system" alt="產品整理後的色彩系統" width={2000} height={1221}/></div><div><h3>另一部門的色彩設定</h3><p>將開發提供的色彩系統納入對照。相同色值可能有不同用途名稱，需要建立清楚的對應關係。</p><Evidence name="department-colors" alt="另一部門提供的 Flutter 色彩設定" width={1756} height={1554}/></div></div></section>
  <section className={styles.section}><div className={styles.sectionHead}><p className={styles.label}>03 / AI-ASSISTED ORGANIZATION</p><h2>讓 AI 協助整理，<br/><span>讓規則能被使用。</span></h2></div><p className={styles.lead}>以既有色彩資料為基礎，運用 AI 協助分類、整理色階與建立取代對照。交付內容同時包含可閱讀的 Markdown 說明與結構化 JSON，讓開發有明確的替換依據。</p><div className={styles.steps}>{[['01','彙整來源','收集設計色票與各部門既有定義。'],['02','整理色階','將零散色值歸納成可管理的分類。'],['03','建立對照','保留原色到新 Token 的替換關係。'],['04','交付開發','以 MD 說明規則，JSON 提供色值。']].map(([n,t,p])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div><div className={styles.stats}>{[['Primary','26','10'],['Neutral','44','11'],['State','34','26']].map(([name,from,to])=><div key={name}><span>{name}</span><strong><s>{from}</s> → {to}</strong><small>整理前 → 整理後色數</small></div>)}</div><p className={styles.caption}>數量依提供的取代對照文件各分類記錄；World Cup Zone 獨立管理，未計入以上分類。</p></section>
  <section className={`${styles.section} ${styles.tinted}`}><div className={styles.sectionHead}><p className={styles.label}>04 / DEVELOPER HANDOFF</p><h2>不只是一張色票，<br/><span>也有替換的方法。</span></h2></div><div className={styles.docs}><article><p className={styles.label}>HUMAN-READABLE</p><h3>color-replacement-guide.md</h3><p>色階整理原則、原色 → Token → 新色的對照，協助開發逐項替換。</p><Evidence name="replacement-guide" alt="AI 整理的色票取代對照 Markdown 文件" width={807} height={841}/></article><article><p className={styles.label}>STRUCTURED DATA</p><h3>design-tokens.json</h3><p>以一致的名稱與結構保存色值，提供後續實作與維護的資料基礎。</p><Evidence name="tokens-json" alt="AI 整理的 Design Tokens JSON" width={805} height={838}/></article></div><p className={styles.caption}>實際交付成果：取代對照文件與 Design Tokens，兼顧閱讀查找與結構化使用。</p></section>
  <section className={styles.section}><div className={styles.sectionHead}><p className={styles.label}>05 / MULTI-BRAND FOUNDATION</p><h2>保留系統，<br/><span>替換品牌色。</span></h2></div><p className={styles.lead}>廠商 Primary color 對應相同的十階命名，透過替換系統 Primary 色值建立廠商樣版，讓品牌延伸有共同的基礎。</p><BrandDemo/><div className={styles.brandEvidence}><Evidence name="brand-primary" alt="12bet 與 ibet 的十階 Primary 品牌色票" width={2000} height={380}/></div></section>
  <section className={`${styles.section} ${styles.closing}`}><p className={styles.label}>A CLEARER FOUNDATION FOR COLLABORATION</p><h2>讓下一次協作，<br/>有一致的起點。</h2><p>這次整理建立了色彩分類、替換對照與品牌色階，為設計維護與跨部門開發提供共同依據。重點是讓既有產品更容易延續，也讓後續品牌樣版能沿用同一套規則。</p><Link href="/work">返回所有作品 ↗</Link></section><PortfolioFooter/>
</main>}
